### ISSUE TITLE
JavaScript error when creating new sample classes

### ISSUE THREAD

**Issue by LisaHagenau** [miso-lims/miso-lims#2587]
Hello,

I was trying to create new sample classes in the web interface and it wouldn't let me add the relationships between stock and aliquot. I then edited the database directly by adding lines to the tables SampleClass and SampleValidRelationship, but now it returns a JavaScript error when I open the new sample classes and it doesn't show the relationships. I am still on version 1.9.1, so maybe just updating would fix it?

Thanks,
Lisa

**Comment by djcooke** [comment]
1.9.1 is quite an old version, so if this is a bug, there's a good chance that it's been fixed in a newer version. That said, I'm guessing it's not a bug.

A lot of validation is performed when attempting to create sample classes and relationships between them to ensure that the sample hierarchy will function as intended. Creating relationships via SQL bypasses this validation. If you're getting Javascript errors, it's likely that you've created an invalid hierarchy, and this is not a bug. What error message were you seeing when you originally tried adding the sample class and relationship?

**Comment by LisaHagenau** [comment]
I don't think I ever got an error message adding the new sample class, it was just that the parent relationsship I wanted to add to the sample class wasn't available. 
More concrete, I first created a new stock sample class "mRNA (stock)" and added "tissue" and "whole RNA (stock)" as parent relationships, which went fine. I then wanted to create the sample class "mRNA (aliquot)" and parent it to "mRNA (stock)", but it was not presented as an option in the popup (I waited a while and tried again in case the database was lagging). That's when I went into the database and added it manually. It should be a valid hierarchy since I only added the stock-aliquot relationship.

**Comment by djcooke** [comment]
Ah, it is a bug that prevented the new options from showing up. There is a constants script that supplies options to many pages in MISO. When sample classes are saved, that script needs to be updated, but the update wasn't being triggered properly. This was fixed in MISO v1.36.1, but there is also a way to force the refresh in previous versions:

1. Log into MISO as an admin user
2. Click your login name at the top right to get to the My Account page
3. In the Administration section, click "Refresh Constants"
4. Click "Refresh" in the dialog to confirm

A confirmation dialog will tell you that the constants have been refreshed, though it may actually take a couple minutes after this.

Alternately, restarting MISO (Tomcat) will also refresh the constants.

The Javascript errors you received after creating sample classes and relationships in the database directly may be due to invalid classes or relationships, or may be due to the constants not having been updated. You can try refreshing the constants, and that may fix the Javascript errors; however, it would be ideal to delete the classes and relationships you created via SQL and re-create them through MISO, as that will ensure that they are valid.

After making any changes to the database directly while MISO is running, make sure to refresh constants, as MISO will otherwise be left in an inconsistent state.

**Comment by LisaHagenau** [comment]
Well, that sounded good, but unfortunately didn't work. I first deleted the sample classes, then recreated the stock class in MISO and refreshed the constants. After around 20 minutes, the sample class was still not appearing in the popup, so I restarted tomcat. Now I can log in, but can only see the menu. 

I uploaded the log files [here](https://nextcloud.uni-greifswald.de/index.php/s/AKdLxNdKi8MatgZ). There are multiple severe errors like this

`07-Dec-2021 09:55:54.494 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [miso] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: Unknown name value [V2.5] for enum class [uk.ac.bbsrc.tgac.miso.core.data.IlluminaChemistry]; nested exception is java.lang.IllegalArgumentException: Unknown name value [V2.5] for enum class [uk.ac.bbsrc.tgac.miso.core.data.IlluminaChemistry]] with root cause`

I vaguely remember changing Illumina Kit versions a while back, but I don't remember exactly what I did.

**Comment by djcooke** [comment]
This looks like a separate issue. The constants aren't able to refresh because there is an invalid chemistry value in the SequencingParameters table in your database. I'm guessing some sequencing parameters were also created via SQL? You'll have to either delete the record or change it to a valid value, which are those in this enum: https://github.com/miso-lims/miso-lims/blob/develop/core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/IlluminaChemistry.java

**Comment by LisaHagenau** [comment]
I removed the rows and restarted MISO and it's working now.

Thank you!
